# src/renderers/pdf_renderer.py
# PDF generation from assembled tearsheet data — Phase 8

from __future__ import annotations

import os
from datetime import date, datetime
from pathlib import Path
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    FrameBreak,
    HRFlowable,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
)
from reportlab.platypus.flowables import Flowable

# ---------------------------------------------------------------------------
# Brand palette
# ---------------------------------------------------------------------------

NAVY  = colors.HexColor("#1B2A4A")
GOLD  = colors.HexColor("#C5A55A")
WHITE = colors.white
GRAY_DARK  = colors.HexColor("#4A4A4A")
GRAY_MID   = colors.HexColor("#767676")
GRAY_LIGHT = colors.HexColor("#F2F2F2")
GRAY_LEGAL = colors.HexColor("#808080")
RED_FLAG   = colors.HexColor("#B22222")
GREEN_FLAG = colors.HexColor("#2E7D32")
AMBER_FLAG = colors.HexColor("#E65100")

# ---------------------------------------------------------------------------
# Page geometry
# ---------------------------------------------------------------------------

PAGE_W, PAGE_H = letter          # 612 × 792 pt
MARGIN_H = 0.65 * inch
MARGIN_TOP = 0.75 * inch
MARGIN_BOT = 0.70 * inch         # footer lives below this
CONTENT_W = PAGE_W - 2 * MARGIN_H

# Header bar height (painted on canvas, not in flow)
HEADER_H = 0.52 * inch

# Disclosure block measurements (reserved at page bottom — NEVER truncated)
DISC_GOLD_RULE_H = 4            # pt
DISC_TOP_PAD    = 6             # pt above first line
DISC_BOTTOM_PAD = 4             # pt below last line
DISC_FONT_SIZE  = 7.5
DISC_LEADING    = 10.5
DISC_LINES_APPROX = 10          # conservative upper-bound for block height calc

# Footer text below disclosure
FOOTER_H = 14                   # pt — "Generated by AltBots [Date]"

OUTPUT_DIR = Path(__file__).resolve().parents[2] / "output"


# ---------------------------------------------------------------------------
# Paragraph styles
# ---------------------------------------------------------------------------

def _build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()

    def S(name, **kw) -> ParagraphStyle:
        parent = kw.pop("parent", "Normal")
        s = ParagraphStyle(name, parent=base[parent], **kw)
        return s

    return {
        # ── Section headings ───────────────────────────────────────────────
        "h1": S("h1",
                fontName="Helvetica-Bold", fontSize=11,
                textColor=NAVY, spaceAfter=4, spaceBefore=10,
                leading=14),
        "h2": S("h2",
                fontName="Helvetica-Bold", fontSize=9,
                textColor=NAVY, spaceAfter=3, spaceBefore=6,
                leading=12),
        "h3": S("h3",
                fontName="Helvetica-BoldOblique", fontSize=8,
                textColor=GRAY_DARK, spaceAfter=2, spaceBefore=4,
                leading=11),

        # ── Body copy ──────────────────────────────────────────────────────
        "body": S("body",
                  fontName="Helvetica", fontSize=8.5,
                  textColor=GRAY_DARK, leading=12, spaceAfter=3),
        "body_sm": S("body_sm",
                     fontName="Helvetica", fontSize=7.5,
                     textColor=GRAY_DARK, leading=10.5, spaceAfter=2),
        "body_italic": S("body_italic",
                         fontName="Helvetica-Oblique", fontSize=8,
                         textColor=GRAY_MID, leading=11, spaceAfter=2),

        # ── Key-value pairs ────────────────────────────────────────────────
        "kv_key": S("kv_key",
                    fontName="Helvetica-Bold", fontSize=7.5,
                    textColor=NAVY, leading=11),
        "kv_val": S("kv_val",
                    fontName="Helvetica", fontSize=7.5,
                    textColor=GRAY_DARK, leading=11),

        # ── Table cells ────────────────────────────────────────────────────
        "tbl_hdr": S("tbl_hdr",
                     fontName="Helvetica-Bold", fontSize=7.5,
                     textColor=WHITE, leading=10),
        "tbl_cell": S("tbl_cell",
                      fontName="Helvetica", fontSize=7.5,
                      textColor=GRAY_DARK, leading=10),
        "tbl_cell_sm": S("tbl_cell_sm",
                         fontName="Helvetica", fontSize=7,
                         textColor=GRAY_DARK, leading=9.5),

        # ── Red flag / signal ──────────────────────────────────────────────
        "flag_body": S("flag_body",
                       fontName="Helvetica", fontSize=8,
                       textColor=GRAY_DARK, leading=11.5, spaceAfter=3),
        "signal_body": S("signal_body",
                         fontName="Helvetica-Oblique", fontSize=8,
                         textColor=GRAY_DARK, leading=11.5, spaceAfter=3),

        # ── Legal disclosure (7.5 pt gray) ─────────────────────────────────
        "legal": S("legal",
                   fontName="Helvetica", fontSize=DISC_FONT_SIZE,
                   textColor=GRAY_LEGAL, leading=DISC_LEADING,
                   spaceAfter=2, alignment=TA_JUSTIFY),
        "legal_bold": S("legal_bold",
                        fontName="Helvetica-Bold", fontSize=DISC_FONT_SIZE,
                        textColor=GRAY_LEGAL, leading=DISC_LEADING,
                        spaceAfter=0),
        "legal_label": S("legal_label",
                         fontName="Helvetica-Bold", fontSize=DISC_FONT_SIZE,
                         textColor=GRAY_LEGAL, leading=DISC_LEADING,
                         spaceAfter=0),

        # ── Misc ───────────────────────────────────────────────────────────
        "badge": S("badge",
                   fontName="Helvetica-Bold", fontSize=7,
                   textColor=WHITE, leading=9, alignment=TA_CENTER),
        "url_sm": S("url_sm",
                    fontName="Helvetica", fontSize=7,
                    textColor=colors.HexColor("#1A5276"),
                    leading=10, spaceAfter=1),
        "footer": S("footer",
                    fontName="Helvetica", fontSize=7,
                    textColor=GRAY_MID, leading=9, alignment=TA_CENTER),
    }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _fmt_usd(value: Optional[int]) -> str:
    if value is None:
        return "—"
    if value >= 1_000_000_000:
        return f"${value / 1_000_000_000:.2f}B"
    if value >= 1_000_000:
        return f"${value / 1_000_000:.1f}M"
    if value >= 1_000:
        return f"${value / 1_000:.0f}K"
    return f"${value:,}"


def _recency_color(flag: str) -> colors.Color:
    return {"green": GREEN_FLAG, "yellow": AMBER_FLAG}.get(flag, RED_FLAG)


def _recency_label(flag: str, days: int) -> str:
    if days < 0:
        return "Unknown date"
    labels = {"green": "Current", "yellow": "Approaching stale", "red": "Stale"}
    return f"{labels.get(flag, 'Stale')} ({days}d ago)"


def _safe_str(val, fallback: str = "—") -> str:
    if val is None:
        return fallback
    s = str(val).strip()
    return s if s else fallback


def _truncate(text: str, max_chars: int) -> str:
    if len(text) <= max_chars:
        return text
    return text[: max_chars - 1] + "…"


def _gold_rule(width: float = CONTENT_W) -> HRFlowable:
    return HRFlowable(width=width, thickness=1, color=GOLD,
                      spaceAfter=4, spaceBefore=4)


def _navy_rule(width: float = CONTENT_W) -> HRFlowable:
    return HRFlowable(width=width, thickness=0.5, color=NAVY,
                      spaceAfter=3, spaceBefore=2)


# ---------------------------------------------------------------------------
# Canvas callbacks — header bar & footer painted on every page
# ---------------------------------------------------------------------------

class _PageDecorator:
    """Callable passed to BaseDocTemplate as onPage / onLaterPages."""

    def __init__(self, manager_name: str, generated_date: str, styles: dict):
        self.manager_name  = manager_name
        self.generated_date = generated_date
        self.styles = styles

    def __call__(self, canvas: Canvas, doc: BaseDocTemplate) -> None:
        canvas.saveState()
        self._draw_header(canvas)
        self._draw_footer(canvas, doc.page)
        canvas.restoreState()

    def _draw_header(self, canvas: Canvas) -> None:
        """Full-width navy header bar with firm name and branding."""
        canvas.setFillColor(NAVY)
        canvas.rect(0, PAGE_H - HEADER_H, PAGE_W, HEADER_H, fill=1, stroke=0)

        # Gold accent rule at bottom of header
        canvas.setStrokeColor(GOLD)
        canvas.setLineWidth(2)
        canvas.line(0, PAGE_H - HEADER_H, PAGE_W, PAGE_H - HEADER_H)

        # Manager name (left)
        canvas.setFillColor(WHITE)
        canvas.setFont("Helvetica-Bold", 13)
        canvas.drawString(MARGIN_H, PAGE_H - HEADER_H + 14,
                          _truncate(self.manager_name, 60))

        # "Intelligence Report" label (right)
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(GOLD)
        canvas.drawRightString(PAGE_W - MARGIN_H, PAGE_H - HEADER_H + 14,
                               "Institutional Intelligence Report")

        # Sub-line: "Prepared by AltBots"
        canvas.setFont("Helvetica-Oblique", 7)
        canvas.setFillColor(colors.HexColor("#A0A8B8"))
        canvas.drawRightString(PAGE_W - MARGIN_H, PAGE_H - HEADER_H + 4,
                               "Prepared by AltBots")

    def _draw_footer(self, canvas: Canvas, page_num: int) -> None:
        """Mandatory footer: 'Generated by AltBots [Date]' + page number."""
        y = MARGIN_BOT - 16
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(GRAY_MID)
        canvas.drawCentredString(
            PAGE_W / 2, y,
            f"Generated by AltBots  {self.generated_date}",
        )
        canvas.drawRightString(PAGE_W - MARGIN_H, y,
                               f"Page {page_num}")


# ---------------------------------------------------------------------------
# Disclosure block builder (four-layer — MUST NOT be truncated)
# ---------------------------------------------------------------------------

def _build_disclosure_block(
    disclosure,               # DisclosureEnvelope
    styles: dict,
) -> list:
    """
    Returns a list of Platypus flowables for the mandatory four-layer
    legal disclosure block.  Preceded by a gold rule separator.
    The block is wrapped in KeepTogether so it will NOT be split across pages
    (it overflows onto a new page wholesale rather than be truncated).
    """
    S = styles

    block: list = []

    # Gold rule separator
    block.append(HRFlowable(
        width=CONTENT_W, thickness=1.5, color=GOLD,
        spaceAfter=DISC_TOP_PAD, spaceBefore=6,
    ))

    # Layer 1 — Not Investment Advice
    block.append(Paragraph(
        "<b>NOT INVESTMENT ADVICE.</b>  " + disclosure.not_investment_advice,
        S["legal"],
    ))

    # Layer 2 — Regulatory / ODD caveat
    block.append(Paragraph(
        "<b>REGULATORY SCREENING LIMITATION.</b>  " + disclosure.regulatory_disclaimer,
        S["legal"],
    ))

    # Layer 3 — Data limitation
    block.append(Paragraph(
        "<b>DATA LIMITATION.</b>  " + disclosure.data_limitation,
        S["legal"],
    ))

    # Layer 4 — Confidentiality
    block.append(Paragraph(
        "<b>CONFIDENTIALITY.</b>  " + disclosure.confidentiality,
        S["legal"],
    ))

    # Data sources line
    if disclosure.data_sources:
        src_txt = "Data sources consulted: " + "; ".join(disclosure.data_sources) + "."
        block.append(Paragraph(src_txt, S["legal"]))

    # Skipped modules
    if disclosure.modules_skipped:
        skipped = "; ".join(
            f"{mod} ({reason})"
            for mod, reason in disclosure.modules_skipped.items()
        )
        block.append(Paragraph(
            f"Modules unavailable during generation: {skipped}.",
            S["legal"],
        ))

    # Version / timestamp
    block.append(Paragraph(
        f"Tearsheet schema v{disclosure.version}  ·  Generated {disclosure.generated_at}",
        S["legal"],
    ))

    block.append(Spacer(1, DISC_BOTTOM_PAD))

    return [KeepTogether(block)]


# ---------------------------------------------------------------------------
# Section builders — Page 1
# ---------------------------------------------------------------------------

def _build_firm_overview(ts, styles: dict) -> list:
    S = styles
    items: list = []

    items.append(Paragraph("Firm Overview", S["h1"]))
    items.append(_navy_rule())

    identity = ts.identity
    edgar    = ts.edgar

    # Key-value grid
    rows = []

    if identity:
        rows.append(("Manager", _safe_str(getattr(identity, "legal_name", None)
                                          or ts.manager_name)))
        if getattr(identity, "crd", None):
            rows.append(("CRD Number", identity.crd))
        if getattr(identity, "cik", None):
            rows.append(("CIK", identity.cik))
        if getattr(identity, "website", None):
            rows.append(("Website", identity.website))
        handles = getattr(identity, "social_handles", {})
        if handles:
            for platform, handle in list(handles.items())[:3]:
                rows.append((platform.title(), _safe_str(handle)))
    else:
        rows.append(("Manager", ts.manager_name))

    if edgar and edgar.adv:
        adv = edgar.adv
        rows.append(("SEC Registered",
                     "Yes" if getattr(adv, "sec_registered", False) else "No"))
        rows.append(("Registration Status",
                     _safe_str(getattr(adv, "registration_status", None))))
        rows.append(("AUM (Total)",
                     _fmt_usd(getattr(adv, "aum_total_usd", None))))
        rows.append(("AUM (Discretionary)",
                     _fmt_usd(getattr(adv, "aum_discretionary_usd", None))))
        if getattr(adv, "num_clients", None) is not None:
            rows.append(("Number of Clients", str(adv.num_clients)))
        if getattr(adv, "min_account_size", None):
            rows.append(("Min Account Size",
                         _safe_str(adv.min_account_size)))
        if getattr(adv, "client_types", None):
            rows.append(("Client Types",
                         _truncate(", ".join(str(c) for c in adv.client_types), 80)))
        if getattr(adv, "fee_structures", None):
            rows.append(("Fee Structures",
                         _truncate(", ".join(str(f) for f in adv.fee_structures), 80)))

    if not rows:
        items.append(Paragraph("No overview data available.", S["body_italic"]))
        return items

    col_w = [1.4 * inch, CONTENT_W - 1.4 * inch]
    tdata = [
        [Paragraph(k, S["kv_key"]), Paragraph(v, S["kv_val"])]
        for k, v in rows
    ]
    tbl = Table(tdata, colWidths=col_w, repeatRows=0)
    tbl.setStyle(TableStyle([
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING",  (0, 0), (-1, -1), 2),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING",   (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 2),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, GRAY_LIGHT]),
        ("GRID",         (0, 0), (-1, -1), 0.25, colors.HexColor("#D0D0D0")),
    ]))
    items.append(tbl)

    # Source attribution
    if edgar and edgar.adv and hasattr(edgar.adv, "source") and edgar.adv.source:
        src = edgar.adv.source
        items.append(Paragraph(
            f"Source: Form ADV · Filed {_safe_str(getattr(src, 'filing_date', None))} · "
            f"Accession {_safe_str(getattr(src, 'accession_number', None))}",
            S["body_italic"],
        ))

    return items


def _build_personnel_table(ts, styles: dict) -> list:
    S = styles
    items: list = []

    items.append(Spacer(1, 8))
    items.append(Paragraph("Key Personnel", S["h1"]))
    items.append(_navy_rule())

    if not ts.personnel:
        items.append(Paragraph("No personnel data available.", S["body_italic"]))
        return items

    headers = ["Name", "Title", "Background"]
    col_w = [1.35 * inch, 1.35 * inch, CONTENT_W - 2.70 * inch]

    tdata: list = [[Paragraph(h, S["tbl_hdr"]) for h in headers]]

    for p in ts.personnel:
        name  = _safe_str(getattr(p, "name", None))
        title = _safe_str(getattr(p, "title", None))
        bio   = _truncate(_safe_str(getattr(p, "bio", None), "No bio available."), 220)
        tdata.append([
            Paragraph(name,  S["tbl_cell"]),
            Paragraph(title, S["tbl_cell"]),
            Paragraph(bio,   S["tbl_cell_sm"]),
        ])

    tbl = Table(tdata, colWidths=col_w, repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR",    (0, 0), (-1, 0), WHITE),
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, GRAY_LIGHT]),
        ("LEFTPADDING",  (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING",   (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 3),
        ("GRID",         (0, 0), (-1, -1), 0.25, colors.HexColor("#C0C0C0")),
    ]))
    items.append(tbl)
    return items


def _build_sec_filings_snapshot(ts, styles: dict) -> list:
    S = styles
    items: list = []

    items.append(Spacer(1, 8))
    items.append(Paragraph("SEC Filings Snapshot", S["h1"]))
    items.append(_navy_rule())

    edgar = ts.edgar
    if not edgar:
        items.append(Paragraph("No SEC filing data available.", S["body_italic"]))
        return items

    # ── 13F holdings ──────────────────────────────────────────────────────
    if edgar.form_13f:
        f13 = edgar.form_13f[0]  # most recent
        items.append(Paragraph("Form 13F — Portfolio Holdings", S["h2"]))
        meta_rows = [
            ("Portfolio Value",
             _fmt_usd(getattr(f13, "total_portfolio_value_usd", None))),
            ("Positions",
             _safe_str(getattr(f13, "num_positions", None))),
            ("Top-10 Concentration",
             f"{f13.concentration_top10_pct:.1f}%"
             if getattr(f13, "concentration_top10_pct", None) is not None
             else "—"),
        ]
        if hasattr(f13, "recency") and f13.recency:
            flag  = getattr(f13.recency, "flag",  "red")
            days  = getattr(f13.recency, "days_since_filing", -1)
            meta_rows.insert(0, ("Recency", _recency_label(flag, days)))

        col_w = [1.4 * inch, CONTENT_W - 1.4 * inch]
        tdata = [[Paragraph(k, S["kv_key"]), Paragraph(v, S["kv_val"])]
                 for k, v in meta_rows]
        tbl = Table(tdata, colWidths=col_w)
        tbl.setStyle(TableStyle([
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, GRAY_LIGHT]),
            ("TOPPADDING",    (0, 0), (-1, -1), 2),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ("LEFTPADDING",   (0, 0), (-1, -1), 2),
            ("GRID",          (0, 0), (-1, -1), 0.25,
             colors.HexColor("#D0D0D0")),
        ]))
        items.append(tbl)

        # Top holdings mini-table
        holdings = getattr(f13, "top_holdings", [])[:8]
        if holdings:
            items.append(Spacer(1, 4))
            items.append(Paragraph("Top Holdings", S["h3"]))
            h_headers = ["Security", "Value", "% of Portfolio"]
            h_col_w = [CONTENT_W * 0.52, CONTENT_W * 0.25, CONTENT_W * 0.23]
            h_data: list = [[Paragraph(h, S["tbl_hdr"]) for h in h_headers]]
            for h in holdings:
                pct = (f"{h.pct_of_portfolio:.2f}%"
                       if getattr(h, "pct_of_portfolio", None) is not None
                       else "—")
                h_data.append([
                    Paragraph(_truncate(_safe_str(getattr(h, "name", None)), 50),
                               S["tbl_cell_sm"]),
                    Paragraph(_fmt_usd(getattr(h, "value_usd", None)),
                               S["tbl_cell_sm"]),
                    Paragraph(pct, S["tbl_cell_sm"]),
                ])
            h_tbl = Table(h_data, colWidths=h_col_w, repeatRows=1)
            h_tbl.setStyle(TableStyle([
                ("BACKGROUND",     (0, 0), (-1, 0), NAVY),
                ("TEXTCOLOR",      (0, 0), (-1, 0), WHITE),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, GRAY_LIGHT]),
                ("TOPPADDING",     (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING",  (0, 0), (-1, -1), 2),
                ("LEFTPADDING",    (0, 0), (-1, -1), 4),
                ("GRID",           (0, 0), (-1, -1), 0.25,
                 colors.HexColor("#C8C8C8")),
            ]))
            items.append(h_tbl)

        if hasattr(f13, "source") and f13.source:
            src = f13.source
            items.append(Paragraph(
                f"Source: {_safe_str(getattr(src, 'form_type', 'Form 13F'))} · "
                f"Filed {_safe_str(getattr(src, 'filing_date', None))} · "
                f"Accession {_safe_str(getattr(src, 'accession_number', None))}",
                S["body_italic"],
            ))

    # ── Form D raises ─────────────────────────────────────────────────────
    if edgar.form_d:
        items.append(Spacer(1, 6))
        items.append(Paragraph("Form D — Private Placement Offerings", S["h2"]))
        d_headers = ["Fund", "Type", "Amount Raised", "First Sale"]
        d_col_w = [CONTENT_W * 0.34, CONTENT_W * 0.22,
                   CONTENT_W * 0.22, CONTENT_W * 0.22]
        d_data: list = [[Paragraph(h, S["tbl_hdr"]) for h in d_headers]]
        for fd in edgar.form_d[:5]:
            d_data.append([
                Paragraph(_truncate(_safe_str(getattr(fd, "fund_name", None)), 40),
                           S["tbl_cell_sm"]),
                Paragraph(_safe_str(getattr(fd, "offering_type", None)),
                           S["tbl_cell_sm"]),
                Paragraph(_fmt_usd(getattr(fd, "amount_raised_usd", None)),
                           S["tbl_cell_sm"]),
                Paragraph(_safe_str(getattr(fd, "date_of_first_sale", None)),
                           S["tbl_cell_sm"]),
            ])
        d_tbl = Table(d_data, colWidths=d_col_w, repeatRows=1)
        d_tbl.setStyle(TableStyle([
            ("BACKGROUND",     (0, 0), (-1, 0), NAVY),
            ("TEXTCOLOR",      (0, 0), (-1, 0), WHITE),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, GRAY_LIGHT]),
            ("TOPPADDING",     (0, 0), (-1, -1), 2),
            ("BOTTOMPADDING",  (0, 0), (-1, -1), 2),
            ("LEFTPADDING",    (0, 0), (-1, -1), 4),
            ("GRID",           (0, 0), (-1, -1), 0.25,
             colors.HexColor("#C8C8C8")),
        ]))
        items.append(d_tbl)

    if not edgar.form_13f and not edgar.form_d and not edgar.adv:
        items.append(Paragraph("No SEC filing records retrieved.", S["body_italic"]))

    return items


# ---------------------------------------------------------------------------
# Section builders — Page 2 (top half)
# ---------------------------------------------------------------------------

def _confidence_badge_para(flag: str, days: int, styles: dict) -> Paragraph:
    """Small inline confidence badge paragraph."""
    label = _recency_label(flag, days)
    col   = _recency_color(flag)
    hex_c = col.hexval() if hasattr(col, "hexval") else "#767676"
    txt = (
        f'<font color="{hex_c}"><b>▮ {label}</b></font>'
    )
    return Paragraph(txt, styles["body_sm"])


def _build_performance_section(ts, styles: dict) -> list:
    """
    Performance section — drawn from 13F data (AUM + holdings) with recency badge.
    The spec calls for a 'confidence badge'; we implement this as a recency badge
    since the tearsheet does not generate performance calculations.
    """
    S = styles
    items: list = []

    items.append(Paragraph("Performance & Portfolio Overview", S["h1"]))
    items.append(_navy_rule())

    edgar = ts.edgar
    if not edgar or not edgar.form_13f:
        items.append(Paragraph(
            "Portfolio performance data not available from public filings.",
            S["body_italic"],
        ))
        return items

    f13 = edgar.form_13f[0]

    # Confidence / recency badge
    if hasattr(f13, "recency") and f13.recency:
        flag = getattr(f13.recency, "flag", "red")
        days = getattr(f13.recency, "days_since_filing", -1)
    elif hasattr(f13, "source") and f13.source:
        filing_date = getattr(f13.source, "filing_date", None)
        if filing_date:
            try:
                from src.core.edgar import filing_recency_flag
                flag, days = filing_recency_flag(str(filing_date))
            except Exception:
                flag, days = "red", -1
        else:
            flag, days = "red", -1
    else:
        flag, days = "red", -1

    items.append(_confidence_badge_para(flag, days, S))
    items.append(Spacer(1, 4))

    rows = [
        ("Reported Portfolio Value",
         _fmt_usd(getattr(f13, "total_portfolio_value_usd", None))),
        ("Number of Positions",
         _safe_str(getattr(f13, "num_positions", None))),
        ("Top-10 Concentration",
         f"{f13.concentration_top10_pct:.1f}%"
         if getattr(f13, "concentration_top10_pct", None) is not None
         else "—"),
    ]

    if edgar.adv:
        adv = edgar.adv
        rows += [
            ("AUM (Total, Form ADV)",
             _fmt_usd(getattr(adv, "aum_total_usd", None))),
            ("AUM (Discretionary)",
             _fmt_usd(getattr(adv, "aum_discretionary_usd", None))),
            ("AUM (Non-Discretionary)",
             _fmt_usd(getattr(adv, "aum_non_discretionary_usd", None))),
        ]

    col_w = [1.8 * inch, CONTENT_W - 1.8 * inch]
    tdata = [[Paragraph(k, S["kv_key"]), Paragraph(v, S["kv_val"])]
             for k, v in rows]
    tbl = Table(tdata, colWidths=col_w)
    tbl.setStyle(TableStyle([
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, GRAY_LIGHT]),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING",   (0, 0), (-1, -1), 4),
        ("GRID",          (0, 0), (-1, -1), 0.25,
         colors.HexColor("#D0D0D0")),
    ]))
    items.append(tbl)

    items.append(Paragraph(
        "Portfolio values are as reported in the most recent Form 13F filing. "
        "Figures represent long positions held at quarter-end and may not reflect "
        "current holdings. This is not a performance record.",
        S["body_italic"],
    ))

    return items


def _build_red_flags_section(ts, styles: dict) -> list:
    S = styles
    items: list = []

    items.append(Spacer(1, 8))
    items.append(Paragraph("Regulatory Disclosures", S["h1"]))
    items.append(_navy_rule())

    rf = ts.red_flags
    if rf is None:
        items.append(Paragraph("Regulatory screening data unavailable.", S["body_italic"]))
        return items

    # Status line
    status_color = RED_FLAG if getattr(rf, "has_disclosures", False) else GREEN_FLAG
    hex_s = status_color.hexval() if hasattr(status_color, "hexval") else "#767676"
    items.append(Paragraph(
        f'<font color="{hex_s}"><b>{rf.status_phrase}</b></font>',
        S["body"],
    ))
    items.append(Spacer(1, 4))

    findings = getattr(rf, "findings", [])
    if not findings:
        items.append(Paragraph(
            "No public regulatory disclosures identified in Form ADV Item 11 "
            "or SEC enforcement records.",
            S["flag_body"],
        ))
    else:
        for idx, finding in enumerate(findings, 1):
            summary     = _safe_str(getattr(finding, "summary", None))
            source_lbl  = _safe_str(getattr(finding, "source_label", None))
            source_url  = _safe_str(getattr(finding, "source_url", None))
            filing_date = getattr(finding, "filing_date", None)
            item_ref    = getattr(finding, "item", None)

            header_parts = [f"({idx})"]
            if item_ref:
                header_parts.append(item_ref)
            if source_lbl and source_lbl != "—":
                header_parts.append(f"— {source_lbl}")
            items.append(Paragraph(" ".join(header_parts), S["h3"]))
            items.append(Paragraph(summary, S["flag_body"]))

            meta_parts = []
            if filing_date:
                meta_parts.append(f"Filing date: {filing_date}")
            if source_url and source_url != "—":
                meta_parts.append(f"Source: {source_url}")
            if meta_parts:
                items.append(Paragraph(" · ".join(meta_parts), S["url_sm"]))
            items.append(Spacer(1, 3))

    # Mandatory red-flag disclaimer
    items.append(Paragraph(
        getattr(rf, "disclaimer",
                "This screening is based on public records and is not exhaustive. "
                "It does not replace a comprehensive Operational Due Diligence review."),
        S["body_italic"],
    ))

    return items


def _build_social_signals_section(ts, styles: dict) -> list:
    S = styles
    items: list = []

    items.append(Spacer(1, 8))
    items.append(Paragraph("Social Signals", S["h1"]))
    items.append(_navy_rule())
    items.append(Paragraph(
        "Observed activity from public sources over the past 90 days.",
        S["body_italic"],
    ))
    items.append(Spacer(1, 4))

    signals = ts.social_signals
    if not signals:
        items.append(Paragraph("No public social signals identified.", S["body_italic"]))
        return items

    for sig in signals[:8]:  # cap display for layout headroom
        title    = _safe_str(getattr(sig, "title", None), "Untitled")
        summary  = _safe_str(getattr(sig, "summary", None), "")
        pub_date = _safe_str(getattr(sig, "published_date", None))
        sig_type = _safe_str(getattr(sig, "signal_type", None))
        source   = _safe_str(getattr(sig, "source", None))
        url      = _safe_str(getattr(sig, "url", None))
        score    = getattr(sig, "relevance_score", None)

        # Header row: title + metadata
        meta = " · ".join(filter(lambda x: x and x != "—",
                                 [pub_date, sig_type.replace("_", " ").title(),
                                  source.replace("_", " ")]))
        items.append(Paragraph(
            f'<b>{_truncate(title, 80)}</b>  '
            f'<font color="#767676" size="7">{meta}</font>',
            S["body"],
        ))
        if summary:
            items.append(Paragraph(
                f"Observed activity: {_truncate(summary, 300)}",
                S["signal_body"],
            ))
        if url and url != "—":
            items.append(Paragraph(url, S["url_sm"]))
        if score is not None:
            items.append(Paragraph(
                f"Relevance score: {score}/10",
                S["body_sm"],
            ))
        items.append(Spacer(1, 5))

    if len(signals) > 8:
        items.append(Paragraph(
            f"… and {len(signals) - 8} additional signal(s) not shown.",
            S["body_italic"],
        ))

    return items


# ---------------------------------------------------------------------------
# Document assembly
# ---------------------------------------------------------------------------

class TearsheetPDFRenderer:
    """
    Renders a Tearsheet object to a two-page PDF.

    Page 1: Header bar · Firm Overview · Key Personnel · SEC Filings Snapshot
    Page 2: Performance (confidence badge) · Red Flags · Social Signals
            [Gold rule] · Four-layer legal disclosure block (NEVER truncated)

    Usage
    -----
    renderer = TearsheetPDFRenderer()
    path = renderer.render(tearsheet)
    print(path)   # /root/tearsheet-project/output/Viking_Global_Investors.pdf
    """

    def __init__(self, output_dir: Optional[Path] = None):
        self.output_dir = Path(output_dir) if output_dir else OUTPUT_DIR
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def render(self, ts) -> str:
        """
        Render the given Tearsheet to a PDF and return the output file path.

        Parameters
        ----------
        ts : Tearsheet
            Must satisfy ts.is_legal_ready (disclosure envelope attached).

        Returns
        -------
        str
            Absolute path of the generated PDF file.

        Raises
        ------
        ValueError
            If ts.disclosure is None (legal check fails).
        """
        if not ts.is_legal_ready:
            raise ValueError(
                "Tearsheet does not carry a DisclosureEnvelope. "
                "Run TearsheetAssembler.assemble() which attaches it as the final step."
            )

        styles = _build_styles()
        generated_date = self._format_date(ts.disclosure.generated_at)
        slug = self._safe_filename(ts.manager_name)
        out_path = str(self.output_dir / f"{slug}.pdf")

        decorator = _PageDecorator(ts.manager_name, generated_date, styles)

        # ── Document template ──────────────────────────────────────────────
        doc = BaseDocTemplate(
            out_path,
            pagesize=letter,
            leftMargin=MARGIN_H,
            rightMargin=MARGIN_H,
            topMargin=HEADER_H + MARGIN_TOP,
            bottomMargin=MARGIN_BOT,
            title=f"{ts.manager_name} — Institutional Tearsheet",
            author="AltBots",
            creator="AltBots Tearsheet Engine v1.0",
        )

        # Single-column frame for both pages
        frame = Frame(
            MARGIN_H, MARGIN_BOT,
            CONTENT_W, PAGE_H - HEADER_H - MARGIN_TOP - MARGIN_BOT,
            leftPadding=0, rightPadding=0,
            topPadding=0, bottomPadding=0,
            id="main",
        )
        template = PageTemplate(
            id="main_template",
            frames=[frame],
            onPage=decorator,
        )
        doc.addPageTemplates([template])

        # ── Build story ────────────────────────────────────────────────────
        story: list = []

        # ── PAGE 1 ─────────────────────────────────────────────────────────
        story += _build_firm_overview(ts, styles)
        story += _build_personnel_table(ts, styles)
        story += _build_sec_filings_snapshot(ts, styles)

        # ── PAGE 2 ─────────────────────────────────────────────────────────
        story.append(PageBreak())
        story += _build_performance_section(ts, styles)
        story += _build_red_flags_section(ts, styles)
        story += _build_social_signals_section(ts, styles)

        # Disclosure block — ALWAYS last; uses KeepTogether so it won't split.
        # Per spec: content compresses/overflows before this block is truncated.
        story += _build_disclosure_block(ts.disclosure, styles)

        doc.build(story)
        return out_path

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    @staticmethod
    def _format_date(iso_str: str) -> str:
        try:
            dt = datetime.fromisoformat(iso_str.replace("Z", "+00:00"))
            return dt.strftime("%B %d, %Y")
        except Exception:
            return str(date.today().strftime("%B %d, %Y"))

    @staticmethod
    def _safe_filename(name: str) -> str:
        safe = "".join(c if c.isalnum() or c in "-_ " else "_" for c in name)
        return safe.replace(" ", "_")[:80]


# ---------------------------------------------------------------------------
# Module-level convenience function
# ---------------------------------------------------------------------------

def render_tearsheet(ts, output_dir: Optional[str] = None) -> str:
    """
    Convenience wrapper: render a Tearsheet object to PDF and return the path.

    Parameters
    ----------
    ts          : Tearsheet (must be legal-ready)
    output_dir  : Optional override for the output directory path.

    Returns
    -------
    str  — absolute path of the generated PDF.
    """
    renderer = TearsheetPDFRenderer(
        output_dir=Path(output_dir) if output_dir else None
    )
    return renderer.render(ts)
